name: 'dbt_medalion_ci_cd_project'
version: '1.0.0'
config-version: 2

profile: 'databricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ============================
# MODELS CONFIG
# ============================
models:
  dbt_medalion_ci_cd_project:

    # ------------------------
    # STAGING (BRONZE)
    # ------------------------
    staging:
      +materialized: view
      +schema: bronze
      +tags: ["staging", "bronze"]

    # ------------------------
    # INTERMEDIATE (SILVER)
    # ------------------------
    intermediate:
      +materialized: table
      +schema: silver
      +tags: ["intermediate", "silver"]

    # ------------------------
    # MARTS (GOLD)
    # ------------------------
    marts:
      +materialized: table
      +schema: gold
      +tags: ["marts", "gold"]

      core:
        +tags: ["customers"]

      finance:
        +tags: ["finance"]

# ============================
# SEEDS CONFIG
# ============================
seeds:
  dbt_medalion_ci_cd_project:
    +schema: raw
    +quote_columns: false
