databricks:
  target: dev
  outputs:

    dev:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'hive_metastore') }}"
      schema: "{{ env_var('DBT_SCHEMA_DEV', 'dev_dbt') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4

    prod:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'hive_metastore') }}"
      schema: "{{ env_var('DBT_SCHEMA_PROD', 'prod_dbt') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4

    pr:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'hive_metastore') }}"
      schema: "{{ env_var('SCHEMA_PREFIX', 'pr') }}_{{ var('schema_id') }}"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
